#!/bin/sh
#
# get-version
#
# Copyright © 2009 Guillem Jover <guillem@hadrons.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THIS_DIR="$(dirname "$0")"

if [ -f "${THIS_DIR}/.dist-version" ]; then
  # Get the version from the file distributed in the tarball.
  version=$(cat "${THIS_DIR}/.dist-version")
elif [ -e "${THIS_DIR}/.git" ]; then
  # Ger the version from the git repository.
  version="$(git --git-dir="${THIS_DIR}/.git" --work-tree="${THIS_DIR}" describe --tags --always --match v[0-9]* 2> /dev/null | tr '-' '.')"

  # Check if we are on a dirty checkout.
  git --git-dir="${THIS_DIR}/.git" --work-tree="${THIS_DIR}" update-index --refresh -q >/dev/null
  dirty="$(git --git-dir="${THIS_DIR}/.git" --work-tree="${THIS_DIR}" diff-index --name-only HEAD 2>/dev/null)"
  if [ -n "$dirty" ]; then
    version="${version}.dirty"
  fi
  version="$(echo "$version" | sed 's/^v//g')"
else
  date +%F
fi

# Use printf to avoid the trailing new line that m4_esyscmd would not handle.
printf "%s" "$version"
